### ISSUE TITLE
Wrong signature call to getCandidates

### ISSUE THREAD

**Issue by rybkine** [PanDAWMS/panda-server#84]
Starting from the
8c3e0347 commit (on the prodanaly branch now also merged into master)
the [call to the getCandidates method](https://github.com/PanDAWMS/panda-server/blob/master/pandaserver/dataservice/EventPicker.py#L217)
in pandaserver/dataservice/EventPicker.py
is not compatible with the [getCandidates definition](https://github.com/PanDAWMS/panda-server/blob/master/pandaserver/dataservice/DynDataDistributer.py#L357)
in pandaserver/dataservice/DynDataDistributer.py

**Comment by fbarreir** [comment]
Should be corrected. I'm waiting to see the next time the event picker runs.

**Comment by rybkine** [comment]
Many thanks. We no longer see the error in our event picking PanDA jobs.
